export PATH="$PATH:/Library/ArchMac/bin"
export MANPATH="$MANPATH:/Library/ArchMac/man"
export PYTHONPATH="$PYTHONPATH:/Library/ArchMac/lib/python2.6/site-packages"
export RUBYLIB="$RUBYLIB:/Library/ArchMac/lib/ruby/site/1.8"
export CFLAGS="$CFLAGS -I/Library/ArchMac/include -L/Library/ArchMac/lib"
